name: Scheduled Workflow

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Current Date and Time
        run: date

      - name: Print Message
        run: echo "This workflow is running automatically every 2 minutes."